# build stage
FROM maven:latest AS build-env
ADD . /src
RUN cd /src/gateway-server && mvn install

# final stage
FROM openjdk:13-jdk-alpine
WORKDIR /app
COPY --from=build-env /src/gateway-server/target /app/
EXPOSE 8760
CMD java -jar gateway-server0.0.1-snapshot.jar