server:
  port: 8762

spring:
  application:
    name: forum-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  oauth2:
    client:
      client-id: spring-setup
      client-secret: spring-secret
      resource-id: oauth2-resource
      access-token-uri: http://localhost:8763/oauth/token
      user-authorization-uri: http://localhost:8763/oauth/authorize
    resource:
      user-info-uri: http://localhost:8763/api/users/me
      token-info-uri: http://localhost:8763/oauth/check_token
      preferTokenInfo: true

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info