server:
  port: 9100
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BlueStone1995/spring-setup-config.git
          username: BlueStone1995
          password: vxF-Rya-sy9-usF